language: python
python:
- "3.7"
dist: xenial
install:
- pip install fs google-api-python-client google-auth pylint pytest python-coveralls coverage
script:
- pylint fs/googledrivefs/
- pylint tests/
- pytest
after_success:
- coveralls
